version: "2"
services:
  flaky-service-1:
    image: rickfast/flaky-service:1
    ports:
      - "8080"
    environment:
      SERVICE_8080_NAME: flaky-service
      SERVICE_8080_HTTP_CHECK: /health
    restart: always
  flaky-service-2:
    image: rickfast/flaky-service:1
    ports:
      - "8080"
    environment:
      SERVICE_8080_NAME: flaky-service
      SERVICE_8080_HTTP_CHECK: /health
    restart: always
  flaky-service-3:
    image: rickfast/flaky-service:1
    ports:
      - "8080"
    environment:
      SERVICE_8080_NAME: flaky-service
      SERVICE_8080_HTTP_CHECK: /health
    restart: always
  registrator:
    image: gliderlabs/registrator:v7
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -ip $DOCKER_IP consul://$DOCKER_IP:8500
    depends_on:
      - consul
    network_mode: host
  consul:
    image: consul:v0.6.4
    command: agent -server -bootstrap -client 0.0.0.0 -advertise $DOCKER_IP -ui
    network_mode: host